CREATE TABLE ALBUMS_REVIEW 
(
  ID_REVIEW INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, REVIEW VARCHAR2(20) NOT NULL 
, CONSTRAINT ALBUMS_REVIEW_PK PRIMARY KEY 
  (
    ID_REVIEW 
  )
  ENABLE 
);

ALTER TABLE ALBUMS_REVIEW ADD CONSTRAINT "fk_Albums_review_ID_User" FOREIGN KEY(ID_USER)
REFERENCES "User" ("ID_User");

ALTER TABLE ALBUMS_REVIEW ADD CONSTRAINT "fk_Albums_review_ID_Album" FOREIGN KEY("ID_Album")
REFERENCES "Compositions" ("ID_Compositions");