DEFINE DATA_TBS_NAME = &&1

CREATE TABLE ALBUMS_REVIEW 
(
  ID_REVIEW INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, REVIEW VARCHAR2(20) NOT NULL 
, CONSTRAINT ALBUMS_REVIEW_PK PRIMARY KEY 
  (
    ID_REVIEW 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

ALTER TABLE ALBUMS_REVIEW ADD CONSTRAINT fk_ALBUMS_REVIEW_ID_User FOREIGN KEY(ID_USER)
REFERENCES Users (ID_USER);

ALTER TABLE ALBUMS_REVIEW ADD CONSTRAINT fk_ALBUMS_REVIEW_ID_ALBUM FOREIGN KEY(ID_ALBUM)
REFERENCES COMPOSITION (ID_COMPOSITION);