DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE COMPOSITION_REVIEW 
(
  ID_REVIEW INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, REVIEW VARCHAR2(50)
, CONSTRAINT COMPOSITON_REVIEW_PK PRIMARY KEY 
  (
    ID_REVIEW 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;

ALTER TABLE COMPOSITION_REVIEW ADD CONSTRAINT fk_COMPOSITION_REVIEW_ID_USER FOREIGN KEY(ID_USER)
REFERENCES Users (ID_USER);

ALTER TABLE COMPOSITION_REVIEW ADD CONSTRAINT fk_COMPOSITION_REVIEW_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES Composition (ID_COMPOSITION);

COMMENT ON COLUMN COMPOSITION_REVIEW.ID_REVIEW IS 'primary key';

COMMENT ON COLUMN COMPOSITION_REVIEW.ID_USER IS 'foreign key from USERS';

COMMENT ON COLUMN COMPOSITION_REVIEW.ID_COMPOSITION IS 'foreign key from COMPOSTION, may be null';

COMMENT ON COLUMN COMPOSITION_REVIEW.REVIEW IS 'just opinion about composition';