DEFINE DATA_TBS_NAME = &&1

CREATE TABLE COMPOSITON_REVIEW 
(
  ID_REVIEW INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, REVIEW VARCHAR2(50) NOT NULL 
, CONSTRAINT COMPOSITON_REVIEW_PK PRIMARY KEY 
  (
    ID_REVIEW 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

ALTER TABLE COMPOSITON_REVIEW ADD CONSTRAINT fk_COMPOSITON_REVIEW_ID_USER FOREIGN KEY(ID_USER)
REFERENCES Users (ID_USER);

ALTER TABLE COMPOSITON_REVIEW ADD CONSTRAINT fk_COMPOSITON_REVIEW_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES Composition (ID_COMPOSITION);