DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TBS_NAME = &&2

CREATE TABLE &&SCHEMA_NAME.COMPOSITON_REVIEW 
(
  ID_REVIEW INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, REVIEW VARCHAR2(50) NOT NULL 
, CONSTRAINT COMPOSITON_REVIEW_PK PRIMARY KEY 
  (
    ID_REVIEW 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

ALTER TABLE &&SCHEMA_NAME.COMPOSITON_REVIEW ADD CONSTRAINT fk_COMPOSITON_REVIEW_ID_User FOREIGN KEY(ID_USER)
REFERENCES &&SCHEMA_NAME.Users (ID_USER);

ALTER TABLE &&SCHEMA_NAME.COMPOSITON_REVIEW ADD CONSTRAINT fk_COMPOSITON_REVIEW_ID_Composition FOREIGN KEY(ID_Composition)
REFERENCES &&SCHEMA_NAME.Composition (ID_Composition);