DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE COMPOSITION 
(
  ID_COMPOSITION INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL 
, NAME_OF_SONG VARCHAR2(20) NOT NULL 
, DURATION_OF_COMPOSITION INT NOT NULL 
, COUNT_OF_LIKES INT NOT NULL 
, COUNT_OF_REPOSTS INT NOT NULL 
, COUNT_OF_LISTENING INT NOT NULL 
, RATING INT NOT NULL 
, GENRE VARCHAR2(20) NOT NULL 
, STYLE VARCHAR2(20) NOT NULL 
, DIRECTION VARCHAR2(20) NOT NULL 
, ID_ALBUM INT NOT NULL 
, CONSTRAINT COMPOSITION_PK PRIMARY KEY 
  (
    ID_COMPOSITION 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;

CREATE UNIQUE INDEX COMPOSITION_ID_COMPOSITION ON COMPOSITION (COMPOSITION_ID_COMPOSITION ASC);

COMMENT ON COLUMN COMPOSITION.RATING IS 'rating in app';

COMMENT ON COLUMN COMPOSITION.GENRE IS 'genre of music';

COMMENT ON COLUMN COMPOSITION.STYLE IS 'style of music';

COMMENT ON COLUMN COMPOSITION.DIRECTION IS 'direction in music';

COMMENT ON COLUMN COMPOSITION.ID_ALBUM IS 'for checking: is the compostion belongs to the album';

COMMENT ON COLUMN COMPOSITION.ID_COMPOSITION IS 'just ID';

COMMENT ON COLUMN COMPOSITION.NAME_OF_SONG IS 'song name';

COMMENT ON COLUMN COMPOSITION.DURATION_OF_COMPOSITION IS 'in seconds';

COMMENT ON COLUMN COMPOSITION.COUNT_OF_LIKES IS 'just count';

COMMENT ON COLUMN COMPOSITION.COUNT_OF_REPOSTS IS 'just count';

COMMENT ON COLUMN COMPOSITION.COUNT_OF_LISTENING IS 'just count';


ALTER TABLE COMPOSITION ADD CONSTRAINT fk_COMPOSITION_ID_ALBUM FOREIGN KEY(ID_ALBUM)
REFERENCES ALBUM (ID_ALBUM);