DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE USERS 
(
  ID_USER INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL 
, FIRST_NAME VARCHAR2(50) NOT NULL 
, SECOND_NAME VARCHAR2(50) NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, PHONE_NUMBER VARCHAR2(50) NOT NULL 
, LOGIN VARCHAR2(50) NOT NULL 
, CONSTRAINT USERS PRIMARY KEY 
  (
    ID_USER 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;

CREATE UNIQUE INDEX USERS_ID_USER ON USERS (USERS_ID_USER ASC);

COMMENT ON COLUMN USERS.ID_USER IS 'Primary key';

COMMENT ON COLUMN USERS.FIRST_NAME IS 'For personal information';

COMMENT ON COLUMN USERS.SECOND_NAME IS 'For personal information';

COMMENT ON COLUMN USERS.EMAIL IS 'For personal information';

COMMENT ON COLUMN USERS.PHONE_NUMBER IS 'For personal information';

COMMENT ON COLUMN USERS.LOGIN IS 'For personal information';