CREATE TABLE PLAYLIST
(
  ID_PLAYLIST INT NOT NULL 
, INCLUDING_ALBUMS VARCHAR2(20) 
, INCLUDING_COMPOSITIONS VARCHAR2(20) NOT NULL 
, PLAYLIST_BY_USER CHAR(1) 
, PLAYLIST_BY_SISTEM CHAR(1) 
, PRIVATE_PLAYLIST CHAR(1) 
, PUBLIC_PLAYLIST CHAR(1) 
, CONSTRAINT PLAYLIST_PK PRIMARY KEY 
  (
    ID_PLAYLIST 
  )
  ENABLE 
);
