CREATE TABLE USERS 
(
  ID_USER INT NOT NULL 
, FIRST_NAME VARCHAR2(50) NOT NULL 
, SECOND_NAME VARCHAR2(50) NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, PHONE_NUMBER VARCHAR2(50) NOT NULL 
, LOGIN VARCHAR2(50) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID_USER 
  )
  ENABLE 
);

COMMENT ON COLUMN USERS.ID_USER IS 'Primary key';

COMMENT ON COLUMN USERS.FIRST_NAME IS 'For personal information';

COMMENT ON COLUMN USERS.SECOND_NAME IS 'For personal information';

COMMENT ON COLUMN USERS.EMAIL IS 'For personal information';

COMMENT ON COLUMN USERS.PHONE_NUMBER IS 'For personal information';

COMMENT ON COLUMN USERS.LOGIN IS 'For personal information';