DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TBS_NAME = &&2

CREATE TABLE &&SCHEMA_NAME.USERS 
(
  ID_USER INT NOT NULL 
, FIRST_NAME VARCHAR2(50) NOT NULL 
, SECOND_NAME VARCHAR2(50) NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, PHONE_NUMBER VARCHAR2(50) NOT NULL 
, LOGIN VARCHAR2(50) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID_USER 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.ID_USER IS 'Primary key';

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.FIRST_NAME IS 'For personal information';

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.SECOND_NAME IS 'For personal information';

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.EMAIL IS 'For personal information';

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.PHONE_NUMBER IS 'For personal information';

COMMENT ON COLUMN &&SCHEMA_NAME.USERS.LOGIN IS 'For personal information';