DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TBS_NAME = &&2

CREATE TABLE SCHEMA_NAME.GENRE 
(
  ID_GENRE INT NOT NULL 
, GENRE VARCHAR2(50) NOT NULL 
, RATING INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, CONSTRAINT GENRE_PK PRIMARY KEY 
  (
    ID_GENRE 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;


ALTER TABLE SCHEMA_NAME.GENRE ADD CONSTRAINT fk_Genre_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES SCHEMA_NAME.COMPOSITION (ID_COMPOSITION);