DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE GENRE 
(
  ID_GENRE INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL 
, GENRE VARCHAR2(50) NOT NULL 
, RATING INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, CONSTRAINT GENRE_PK PRIMARY KEY 
  (
    ID_GENRE 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;


ALTER TABLE GENRE ADD CONSTRAINT fk_GENRE_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES COMPOSITION (ID_COMPOSITION);

CREATE UNIQUE INDEX GENRE_ID_COMPOSITION ON GENRE (ID_COMPOSITION ASC);

COMMENT ON COLUMN GENRE.ID_GENRE IS 'primary key';

COMMENT ON COLUMN GENRE.GENRE IS 'type of composition';

COMMENT ON COLUMN GENRE.RATING IS 'just digit';

COMMENT ON COLUMN GENRE.ID_COMPOSITION IS 'foreign key from composition';
