DEFINE DATA_TBS_NAME = &&1

CREATE TABLE PLAYLIST_CONTAIN 
(
  ID_CONTAIN INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_PLAYLIST INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, CONSTRAINT PLAYLIST_CONTAIN PRIMARY KEY 
  (
    ID_CONTAIN 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT fk_PLAYLIST_CONTAIN_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES COMPOSITION (ID_COMPOSITION);

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT fk_PLAYLIST_CONTAIN_ID_PLAYLIST FOREIGN KEY(ID_PLAYLIST)
REFERENCES PLAYLIST (ID_PLAYLIST);

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT fk_PLAYLIST_CONTAIN_ID_ALBUM FOREIGN KEY(ID_ALBUM)
REFERENCES ALBUM (ID_ALBUM);