DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TBS_NAME = &&2

CREATE TABLE &&SCHEMA_NAME.PLAYLIST_CONTAIN 
(
  ID_CONTAIN INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_PLAYLIST INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, CONSTRAINT PLAYLIST_CONTAIN PRIMARY KEY 
  (
    ID_CONTAIN 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

ALTER TABLE &&SCHEMA_NAME.PLAYLIST_CONTAIN ADD CONSTRAINT fk_Playlist_contain_ID_Composition FOREIGN KEY(ID_Compositions)
REFERENCES &&SCHEMA_NAME.Composition (ID_Composition);

ALTER TABLE &&SCHEMA_NAME.PLAYLIST_CONTAIN ADD CONSTRAINT fk_Playlist_contain_ID_playlist FOREIGN KEY(ID_playlist)
REFERENCES &&SCHEMA_NAME.Playlist (ID_Playlist);

ALTER TABLE &&SCHEMA_NAME.PLAYLIST_CONTAIN ADD CONSTRAINT fk_Playlist_contain_ID_Album FOREIGN KEY(ID_Album)
REFERENCES &&SCHEMA_NAME.Album (ID_Album);