CREATE TABLE PLAYLIST_CONTAIN 
(
  ID_CONTAIN INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_PLAYLIST INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, CONSTRAINT PLAYLIST_CONTAIN_PK PRIMARY KEY 
  (
    ID_CONTAIN 
  )
  ENABLE 
);

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT fk_PLAYLIST_CONTAIN_ID_Composition FOREIGN KEY(ID_COMPOSITION)
REFERENCES Composition (ID_COMPOSITION);

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT fk_PLAYLIST_CONTAIN_ID_PLAYLIST FOREIGN KEY(ID_PLAYLIST)
REFERENCES PLAYLIST (ID_PLAYLIST);

ALTER TABLE PLAYLIST_CONTAIN ADD CONSTRAINT "fk_Playlist_contain_ID_Album" FOREIGN KEY(ID_ALBUM)
REFERENCES ALBUM (ID_ALBUM);