DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE STORY_OF_LISTENING 
(
  ID_STORY INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, DATE_OF_LISTENING DATE NOT NULL 
, CONSTRAINT ST_PK PRIMARY KEY 
  (
    ID_STORY 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;

ALTER TABLE STORY_OF_LISTENING ADD CONSTRAINT fk_STORY_OF_LISTENING_ID_USER FOREIGN KEY(ID_USER)
REFERENCES USERS (ID_USER);

ALTER TABLE STORY_OF_LISTENING ADD CONSTRAINT fk_STORY_OF_LISTENING_ID_ALBUM FOREIGN KEY(ID_ALBUM)
REFERENCES ALBUM (ID_ALBUM);

CREATE UNIQUE INDEX STORY_OF_LISTENING_ID_COMPOSITION ON STORY_OF_LISTENING (ID_COMPOSITION ASC);
CREATE UNIQUE INDEX STORY_OF_LISTENING_ID_USER ON STORY_OF_LISTENING (ID_USER ASC);
CREATE UNIQUE INDEX STORY_OF_LISTENING_ID_ALBUM ON STORY_OF_LISTENING (ID_ALBUM ASC);

COMMENT ON COLUMN STORY_OF_LISTENING.ID_STORY IS 'primary key';

COMMENT ON COLUMN STORY_OF_LISTENING.ID_USER IS 'foreign key from users';

COMMENT ON COLUMN STORY_OF_LISTENING.ID_COMPOSITION IS 'foreign key from composition';

COMMENT ON COLUMN STORY_OF_LISTENING.ID_ALBUM IS 'foreign key from album';

COMMENT ON COLUMN STORY_OF_LISTENING.DATE_OF_LISTENING IS 'just date of listening';

