DEFINE DATA_TBS_NAME = &&1

CREATE TABLE USER_STATE 
(
  ID_STATE INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, CURRENT_COMPOSITION VARCHAR2(20) NOT NULL 
, CURRENT_PLAYLIST VARCHAR2(20) 
, STOPPING_TIME INT 
, CONSTRAINT USER_STATE_PK PRIMARY KEY 
  (
    ID_STATE 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

COMMENT ON COLUMN USER_STATE.CURRENT_COMPOSITION IS 'current composition in playlist';

COMMENT ON COLUMN USER_STATE.STOPPING_TIME IS 'time when use is stopped';

ALTER TABLE USER_STATE ADD CONSTRAINT fk_USER_STATE_ID_USER FOREIGN KEY(ID_USER)
REFERENCES Users (ID_User);

ALTER TABLE USER_STATE ADD CONSTRAINT fk_USER_STATE_ID_COMPOSITION FOREIGN KEY(ID_COMPOSITION)
REFERENCES COMPOSITION (ID_COMPOSITION);

ALTER TABLE USER_STATE ADD CONSTRAINT fk_USER_STATE_ID_ALBUM FOREIGN KEY(ID_ALBUM)
REFERENCES ALBUM (ID_ALBUM);