DEFINE SCHEMA_NAME = &&1
DEFINE DATA_TBS_NAME = &&2

CREATE TABLE &&SCHEMA_NAME.USER_PLAYLIST 
(
  ID_UP INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_PLAYLIST INT NOT NULL 
, CONSTRAINT USER_PLAYLIST_PK PRIMARY KEY 
  (
    ID_UP 
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME;

COMMENT ON COLUMN &&SCHEMA_NAME.USER_PLAYLIST.ID_UP IS 'id for user playlist';

ALTER TABLE &&SCHEMA_NAME.USER_PLAYLIST ADD CONSTRAINT fk_USER_PLAYLIST_ID_USER FOREIGN KEY(ID_USER)
REFERENCES &&SCHEMA_NAME.Users (ID_USER);

ALTER TABLE &&SCHEMA_NAME.USER_PLAYLIST ADD CONSTRAINT fk_USER_PLAYLIST_ID_playlist FOREIGN KEY(ID_playlist)
REFERENCES &&SCHEMA_NAME.PLAYLIST (ID_Playlist);