CREATE TABLE USER_PLAYLIST 
(
  ID_UP INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_PLAYLIST INT NOT NULL 
, CONSTRAINT USER_PLAYLIST_PK PRIMARY KEY 
  (
    ID_UP 
  )
  ENABLE 
);

COMMENT ON COLUMN USER_PLAYLIST.ID_UP IS 'id for user playlist';

ALTER TABLE USER_PLAYLIST ADD CONSTRAINT fk_USER_PLAYLIST_ID_USER FOREIGN KEY(ID_USER)
REFERENCES Users (ID_USER);

ALTER TABLE USER_PLAYLIST ADD CONSTRAINT fk_USER_PLAYLIST_ID_playlist FOREIGN KEY(ID_playlist)
REFERENCES PLAYLIST (ID_Playlist);