CREATE TABLE USER_STATE 
(
  ID_STATE INT NOT NULL 
, ID_USER INT NOT NULL 
, ID_COMPOSITION INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, CURRENT_COMPOSITION VARCHAR2(20) NOT NULL 
, CURRENT_PLAYLIST VARCHAR2(20) 
, STOPPING_TIME INT 
, CONSTRAINT USER_STATE_PK PRIMARY KEY 
  (
    ID_STATE 
  )
  ENABLE 
);

COMMENT ON COLUMN USER_STATE.CURRENT_COMPOSITION IS 'current composition in playlist';

COMMENT ON COLUMN USER_STATE.STOPPING_TIME IS 'time when use is stopped';

ALTER TABLE USER_STATE ADD CONSTRAINT fk_User_state_ID_User FOREIGN KEY(ID_User)
REFERENCES Users (ID_User);

ALTER TABLE USER_STATE ADD CONSTRAINT fk_User_state_ID_Composition FOREIGN KEY(ID_Composition)
REFERENCES Composition (ID_Composition);

ALTER TABLE USER_STATE ADD CONSTRAINT fk_User_state_ID_Album FOREIGN KEY(ID_Album)
REFERENCES Album (ID_Album);