DEFINE TABLESPACE_NAME = &&1
DEFINE TBS_LOCATION =  &&2
DEFINE EXT = '.dbf'
DEFINE CURS = '_DATA'
DEFINE CURS1 = '_IDX'


  CREATE SMALLFILE TABLESPACE &&TABLESPACE_NAME&CURS
  DATAFILE '&&TBS_LOCATION\&&TABLESPACE_NAME&CURS&EXT'
  SIZE 10M AUTOEXTEND ON NEXT 10 
  MAXSIZE 5120M EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
  MANAGEMENT AUTO;
  
  
  CREATE SMALLFILE TABLESPACE &&TABLESPACE_NAME&CURS1
  DATAFILE '&&TBS_LOCATION\&&TABLESPACE_NAME&CURS1&EXT'
  SIZE 10M AUTOEXTEND ON NEXT 10 
  MAXSIZE 5120M EXTENT MANAGEMENT LOCAL SEGMENT SPACE 
  MANAGEMENT AUTO;