CREATE TABLE TABLE1 
(
  ID_COMPOSITION INT NOT NULL 
, ID_ALBUM INT NOT NULL 
, DURATION INT 
, COUNT_OF_LIKES INT 
, COUNT_OF_REPOSTS INT 
, REWIEW VARCHAR2(100) 
, COUNT_OF_LISTENING INT 
, RATING INT 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID_COMPOSITION 
  )
  ENABLE 
);
