CREATE TABLE PLAYLIST 
(
  ID_PLAYLIST INT NOT NULL 
, ID_USER INT NOT NULL 
, INCLUDED_ALBUMS VARCHAR2(100) 
, INCLUDED_COMPOSITIONS VARCHAR2(20) 
, CONSTRAINT PLAYLIST_PK PRIMARY KEY 
  (
    ID_PLAYLIST 
  )
  ENABLE 
);