CREATE TABLE SERVICE_USER 
(
  ID_USER INT NOT NULL 
, NAME VARCHAR2(50) NOT NULL 
, SECOND_NAME VARCHAR2(50) NOT NULL 
, EMAIL VARCHAR2(50) NOT NULL 
, PHNUMBER VARCHAR2(50) NOT NULL 
, LOGIN VARCHAR2(50) NOT NULL 
, CONSTRAINT USER1_PK PRIMARY KEY 
  (
    ID_USER 
  )
  ENABLE 
);