CREATE TABLE ALBUM 
(
  ID_ALBUM INT NOT NULL 
, COUNT_OF_LIKES INT 
, COUNT_OF_LISTENING INT 
, COUNT_OF_REPOSTS INT 
, RAITING INT 
, CONSTRAINT ALBUM_PK PRIMARY KEY 
  (
    ID_ALBUM 
  )
  ENABLE 
);
