DEFINE DATA_TBS_NAME = &&1
DEFINE CURS = '_DATA'

CREATE TABLE EXDATA ( 
  ID_EXDATA INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOMAXVALUE NOT NULL, 
  FIRST_NAME VARCHAR2(26),
  LAST_NAME VARCHAR2(126),
  NICKNAME VARCHAR2(126),
  EMAIL VARCHAR2(126),
  PLAYLIST_NAME VARCHAR2(126),
  PLAYLIST_TYPE VARCHAR2(126),
  MUSIC_TYPE VARCHAR2(126),
  COMPOSITION_NAME VARCHAR2(128),
  lENGTH FLOAT,
  OWNER_FIRST_NAME VARCHAR2(126),
  OWNER_LAST_NAME VARCHAR2(126),
  OWNER_NICKNAME VARCHAR2(126),
  LIKES VARCHAR2(5),
  COMPOSITION_LIKES INT,
  LISTEN FLOAT,
  COMMENTS_TRACK VARCHAR2(126),
  CURRENT_LISTENING VARCHAR2(126),
  STOPPED_TIME FLOAT,
  CONSTRAINT EXDATA_PK PRIMARY KEY 
  (
    ID_EXDATA
  )
  ENABLE 
)
TABLESPACE &&DATA_TBS_NAME&&CURS;
