DEFINE SCHEMA_NAME = &&1

INSERT INTO &&SCHEMA_NAME.USERS VALUES(1, "Vladimir", "Petrov", "petr@gmail.com", "12312421", "vladpetr");
INSERT INTO &&SCHEMA_NAME.USERS VALUES(2, "Semen", "Slepakov", "slep@gmail.com", "1236521", "semslep");

INSERT INTO &&SCHEMA_NAME.COMPOSITION VALUES(1,"Nirvana",140,12,421,412,2, "rock", "metal", "reggy");
INSERT INTO &&SCHEMA_NAME.COMPOSITION VALUES(1,"Lullaby",120,162,4210,42,1, "rock", "pop-rock", "alternative");

INSERT INTO &&SCHEMA_NAME.ALBUM VALUES (1,150,20,1000,2);
INSERT INTO &&SCHEMA_NAME.ALBUM VALUES (2,450,200,1010,1);

INSERT INTO &&SCHEMA_NAME.PLAYLIST VALUES(1,"Revival", "River", "Y", "N", "N", "N");
INSERT INTO &&SCHEMA_NAME.PLAYLIST VALUES(1,"Love Me Do", "Yellow submarine", "N", "Y", "Y", "Y");

INSERT INTO &&SCHEMA_NAME.ALBUMS_REVIEW VALUES(1,1,1,"good");
INSERT INTO &&SCHEMA_NAME.ALBUMS_REVIEW VALUES(2,2,2,"well");

INSERT INTO &&SCHEMA_NAME.COMPOSITON_REVIEW VALUES(1,1,1,"so-so");
INSERT INTO &&SCHEMA_NAME.COMPOSITON_REVIEW VALUES(2,2,2,"good job");

INSERT INTO &&SCHEMA_NAME.GENRE VALUES(1, "rock", 1,1);
INSERT INTO &&SCHEMA_NAME.GENRE VALUES(2, "rock", 1,2);

INSERT INTO &&SCHEMA_NAME.PLAYLIST_CONTAIN VALUES(1,1,1,1);
INSERT INTO &&SCHEMA_NAME.PLAYLIST_CONTAIN VALUES(2,2,2,2);

INSERT INTO &&SCHEMA_NAME.STORY_OF_LISTENING VALUES(1,1,1,1,'11/01/2020');
INSERT INTO &&SCHEMA_NAME.STORY_OF_LISTENING VALUES(2,2,2,2,'15/03/2020');

INSERT INTO &&SCHEMA_NAME.USER_PLAYLIST VALUES(1,1,1);
INSERT INTO &&SCHEMA_NAME.USER_PLAYLIST VALUES(2,2,2);

INSERT INTO &&SCHEMA_NAME.USER_STATE VALUES(1,1,1,1, "nirvana","",13);
INSERT INTO &&SCHEMA_NAME.USER_STATE VALUES(2,2,2,2, "Lullaby","",26);