
INSERT INTO USERS(FIRST_NAME, SECOND_NAME, EMAIL, PHONE_NUMBER, LOGIN) VALUES('Vladimir', 'Petrov', 'petr@gmail.com', '12312421', 'vladpetr');
INSERT INTO USERS(FIRST_NAME, SECOND_NAME, EMAIL, PHONE_NUMBER, LOGIN) VALUES('Semen', 'Slepakov', 'slep@gmail.com', '1236521', 'semslep');

INSERT INTO ALBUM(COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING) VALUES (150,20,1000,2);
INSERT INTO ALBUM(COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING) VALUES (450,200,1010,1);

INSERT INTO COMPOSITION(NAME_OF_SONG, DURATION_OF_COMPOSITION, COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING, GENRE, STYLE, DIRECTION, ID_ALBUM) VALUES('Nirvana',140,12,421,412,2, 'rock', 'metal', 'reggy', 1);
INSERT INTO COMPOSITION(NAME_OF_SONG, DURATION_OF_COMPOSITION, COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING, GENRE, STYLE, DIRECTION, ID_ALBUM) VALUES('Lullaby',120,162,4210,42,1, 'rock', 'pop-rock', 'alternative', 2);

INSERT INTO PLAYLIST(INCLUDING_ALBUMS, INCLUDING_COMPOSITIONS, PLAYLIST_BY_USER, PLAYLIST_BY_SYSTEM, PRIVATE_PLAYLIST, PUBLIC_PLAYLIST) VALUES('Revival', 'River', 'Y', 'N', 'N', 'N');
INSERT INTO PLAYLIST(INCLUDING_ALBUMS, INCLUDING_COMPOSITIONS, PLAYLIST_BY_USER, PLAYLIST_BY_SYSTEM, PRIVATE_PLAYLIST, PUBLIC_PLAYLIST) VALUES('Love Me Do', 'Yellow submarine', 'N', 'Y', 'Y', 'Y');

INSERT INTO ALBUMS_REVIEW(ID_USER, ID_ALBUM, REVIEW) VALUES(1,1,'good');
INSERT INTO ALBUMS_REVIEW(ID_USER, ID_ALBUM, REVIEW) VALUES(2,2,'well');

INSERT INTO COMPOSITON_REVIEW(ID_USER, ID_COMPOSITION, REVIEW) VALUES(1,1,'so-so');
INSERT INTO COMPOSITON_REVIEW(ID_USER, ID_COMPOSITION, REVIEW) VALUES(2,2,'good job');

INSERT INTO GENRE(GENRE, RATING, ID_COMPOSITION) VALUES( 'rock', 1,1);
INSERT INTO GENRE(GENRE, RATING, ID_COMPOSITION) VALUES( 'rock', 1,2);

INSERT INTO PLAYLIST_CONTAIN(ID_COMPOSITION, ID_PLAYLIST, ID_ALBUM) VALUES(1,1,1);
INSERT INTO PLAYLIST_CONTAIN(ID_COMPOSITION, ID_PLAYLIST, ID_ALBUM) VALUES(2,2,2);

INSERT INTO STORY_OF_LISTENING(ID_USER, ID_COMPOSITION, ID_ALBUM, DATE_OF_LISTENING) VALUES(1,1,1,TO_DATE('01/01/2020'));
INSERT INTO STORY_OF_LISTENING(ID_USER, ID_COMPOSITION, ID_ALBUM, DATE_OF_LISTENING) VALUES(2,2,2,TO_DATE('02/02/2020'));

INSERT INTO USER_PLAYLIST(ID_USER, ID_PLAYLIST) VALUES(1,1);
INSERT INTO USER_PLAYLIST(ID_USER, ID_PLAYLIST) VALUES(2,2);

INSERT INTO USER_STATE(ID_USER, ID_COMPOSITION, ID_ALBUM, CURRENT_COMPOSITION, CURRENT_PLAYLIST, STOPPING_TIME) VALUES(1,1,1, 'nirvana','',13);
INSERT INTO USER_STATE(ID_USER, ID_COMPOSITION, ID_ALBUM, CURRENT_COMPOSITION, CURRENT_PLAYLIST, STOPPING_TIME) VALUES(2,2,2, 'Lullaby','',26);