INSERT INTO EXDATA (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, MUSIC_TYPE, COMPOSITION_NAME, LENGTH, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKES, COMPOSITION_LIKES, LISTEN, COMMENTS_TRACK, CURRENT_LISTENING, STOPPED_TIME)
            VALUES ('Elizaveta','Rapinchuk','Bug','Circle_Bug@gmail.com','Sport','System','Sport','Ten Walls - Sparta',3.44,'Ten','Walls','Monsieur','no',88,22000,'Очень серьезный кач','Y',2.01);
INSERT INTO EXDATA (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, MUSIC_TYPE, COMPOSITION_NAME, LENGTH, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKES, COMPOSITION_LIKES, LISTEN, COMMENTS_TRACK, CURRENT_LISTENING, STOPPED_TIME) VALUES 
('Elizaveta','Rapinchuk','Bug','Circle_Bug@gmail.com','Bamboo','User','Chill','Murda On They Mind (Tales From Mount Zion)',3.02,NULL,NULL,'DJ Bishop','yes',3306,540050,NULL,NULL,NULL);
INSERT INTO EXDATA (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, MUSIC_TYPE, COMPOSITION_NAME, LENGTH, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKES, COMPOSITION_LIKES, LISTEN, COMMENTS_TRACK, CURRENT_LISTENING, STOPPED_TIME) VALUES 
('Elizaveta','Rapinchuk','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','James Blake - Air Lack Thereof',4.09,'H?lder','Leal','Hotshot','no',4455,1433,NULL,NULL,NULL);
INSERT INTO EXDATA (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, MUSIC_TYPE, COMPOSITION_NAME, LENGTH, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKES, COMPOSITION_LIKES, LISTEN, COMMENTS_TRACK, CURRENT_LISTENING, STOPPED_TIME) VALUES 
('Elizaveta','Rapinchuk','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Little Fish',2.13,'H?lder','Leal','Hotshot','yes',6587,8890,NULL,NULL,NULL);
INSERT INTO EXDATA (FIRST_NAME, LAST_NAME, NICKNAME, EMAIL, PLAYLIST_NAME, PLAYLIST_TYPE, MUSIC_TYPE, COMPOSITION_NAME, LENGTH, OWNER_FIRST_NAME, OWNER_LAST_NAME, OWNER_NICKNAME, LIKES, COMPOSITION_LIKES, LISTEN, COMMENTS_TRACK, CURRENT_LISTENING, STOPPED_TIME) VALUES 
('Elizaveta','Rapinchuk','Bug','Circle_Bug@gmail.com','Bamboo','User','Electronic','Jamie XX - Loud Places (feat. Romy)',4.43,'H?lder','Leal','Hotshot','no',2201,202023,NULL,NULL,NULL);


INSERT INTO USERS(FIRST_NAME, SECOND_NAME, EMAIL, LOGIN) VALUES('Semen', 'Slepakov', 'slep@gmail.com', 'semslep');
INSERT INTO USERS(FIRST_NAME, SECOND_NAME, EMAIL, LOGIN) VALUES('Semen', 'Slepakov', 'slep@gmail.com', 'semslep');

INSERT INTO ALBUM(COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING) VALUES (150,20,1000,2);
INSERT INTO ALBUM(COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING) VALUES (450,200,1010,1);

INSERT INTO COMPOSITION(NAME_OF_SONG, DURATION_OF_COMPOSITION, COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING, GENRE, STYLE, DIRECTION, ID_ALBUM) VALUES('Nirvana',140,12,421,412,2, 'rock', 'metal', 'reggy', 1);
INSERT INTO COMPOSITION(NAME_OF_SONG, DURATION_OF_COMPOSITION, COUNT_OF_LIKES, COUNT_OF_REPOSTS, COUNT_OF_LISTENING, RATING, GENRE, STYLE, DIRECTION, ID_ALBUM) VALUES('Lullaby',120,162,4210,42,1, 'rock', 'pop-rock', 'alternative', 2);

INSERT INTO PLAYLIST(PLAYLIST_BY_USER, PLAYLIST_BY_SYSTEM, PRIVATE_PLAYLIST, PUBLIC_PLAYLIST) VALUES( 'Y', 'N', 'N', 'N');
INSERT INTO PLAYLIST(PLAYLIST_BY_USER, PLAYLIST_BY_SYSTEM, PRIVATE_PLAYLIST, PUBLIC_PLAYLIST) VALUES( 'N', 'Y', 'Y', 'Y');

INSERT INTO ALBUMS_REVIEW(ID_USER, ID_ALBUM, REVIEW) VALUES(1,1,'good');
INSERT INTO ALBUMS_REVIEW(ID_USER, ID_ALBUM, REVIEW) VALUES(2,2,'well');

INSERT INTO COMPOSITON_REVIEW(ID_USER, ID_COMPOSITION, REVIEW) VALUES(1,1,'so-so');
INSERT INTO COMPOSITON_REVIEW(ID_USER, ID_COMPOSITION, REVIEW) VALUES(2,2,'good job');

INSERT INTO GENRE(GENRE, RATING, ID_COMPOSITION) VALUES( 'rock', 1,1);
INSERT INTO GENRE(GENRE, RATING, ID_COMPOSITION) VALUES( 'rock', 1,2);

INSERT INTO PLAYLIST_CONTAIN(ID_COMPOSITION, ID_PLAYLIST, ID_ALBUM) VALUES(1,1,1);
INSERT INTO PLAYLIST_CONTAIN(ID_COMPOSITION, ID_PLAYLIST, ID_ALBUM) VALUES(2,2,2);

INSERT INTO STORY_OF_LISTENING(ID_USER, ID_COMPOSITION, ID_ALBUM, DATE_OF_LISTENING) VALUES(1,1,1, TO_DATE('01-01-2020','DD-MM-YYYY'));
INSERT INTO STORY_OF_LISTENING(ID_USER, ID_COMPOSITION, ID_ALBUM, DATE_OF_LISTENING) VALUES(2,2,2, TO_DATE('02-02-2020', 'DD-MM-YYYY'));

INSERT INTO USER_PLAYLIST(ID_USER, ID_PLAYLIST) VALUES(1,1);
INSERT INTO USER_PLAYLIST(ID_USER, ID_PLAYLIST) VALUES(2,2);

INSERT INTO USER_STATE(ID_USER, ID_COMPOSITION, ID_ALBUM, CURRENT_COMPOSITION, CURRENT_PLAYLIST, STOPPING_TIME) VALUES(1,1,1, 'nirvana','',13);
INSERT INTO USER_STATE(ID_USER, ID_COMPOSITION, ID_ALBUM, CURRENT_COMPOSITION, CURRENT_PLAYLIST, STOPPING_TIME) VALUES(2,2,2, 'Lullaby','',26);