PROMPT ====CREATE_USER====
DEFINE USER_NAME = &&1
DEFINE PASSWORD =  'oracle'
DEFINE CURS = '_DATA'

CREATE USER &USER_NAME identified by &PASSWORD DEFAULT TABLESPACE &&USER_NAME&&CURS
  TEMPORARY TABLESPACE temp
    QUOTA 100M on &&USER_NAME&&CURS;


PROMPT ====CREATE_USER_FINISHED====