DEFINE TABLESPACE_NAME = &&1
DEFINE CURS = '_DATA'
DEFINE CURS1 = '_IDX'

DROP TABLESPACE &&TABLESPACE_NAME&&CURS
    INCLUDING CONTENTS 
        CASCADE CONSTRAINTS; 

DROP TABLESPACE &&TABLESPACE_NAME&&CURS1
    INCLUDING CONTENTS 
        CASCADE CONSTRAINTS; 