DEFINE TABLESPACE_NAME = &&1
DEFINE CURS = '_DATA'
DEFINE CURS1 = '_IDX'
PROMPT 'Drop is begin'
DROP TABLESPACE &&TABLESPACE_NAME&&CURS
    INCLUDING CONTENTS 
        CASCADE CONSTRAINTS; 
PROMPT 'DATA tablespace dropped'
DROP TABLESPACE &&TABLESPACE_NAME&&CURS1
    INCLUDING CONTENTS 
        CASCADE CONSTRAINTS; 
PROMPT 'IDX tablespace dropped'
